[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x1ee592601cde2eb4147136aadf1f2f07d4519d510e0cd013a4339dd09a1e192"
transaction_hash = "0x504f5faa64ad5218038b2ba2578751ab1b80a6a489fa35afe1c7247190736cf"
block_number = 3
seed = "mancala"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
class_hash = "0x39d1eb5e9172f84093382dc14cbe405b801668ecebe983029618aba18fe7209"
original_class_hash = "0x39d1eb5e9172f84093382dc14cbe405b801668ecebe983029618aba18fe7209"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "mancala::systems::actions::actions"

[[contracts]]
kind = "DojoContract"
class_hash = "0x55d9c7d73ce5320b6a5a333abe55319e50c0bf856630ef2e21b378d954ed6cf"
original_class_hash = "0x55d9c7d73ce5320b6a5a333abe55319e50c0bf856630ef2e21b378d954ed6cf"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/mancala_systems_test_actions_test_actions.json"
reads = []
writes = []
computed = []
name = "mancala::systems::test_actions::test_actions"

[[models]]
kind = "DojoModel"
class_hash = "0x29ed79ab8023a4bc637b430729cc7fae34e88f754de9cc587f44b082fefab73"
original_class_hash = "0x29ed79ab8023a4bc637b430729cc7fae34e88f754de9cc587f44b082fefab73"
abi = "abis/deployments/models/mancala_models_game_game.json"
name = "mancala::models::game::game"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_one"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_two"
type = "ContractAddress"
key = false

[[models.members]]
name = "current_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "score"
type = "u8"
key = false

[[models.members]]
name = "is_finished"
type = "bool"
key = false

[[models.members]]
name = "p1_pit1"
type = "u8"
key = false

[[models.members]]
name = "p1_pit2"
type = "u8"
key = false

[[models.members]]
name = "p1_pit3"
type = "u8"
key = false

[[models.members]]
name = "p1_pit4"
type = "u8"
key = false

[[models.members]]
name = "p1_pit5"
type = "u8"
key = false

[[models.members]]
name = "p1_pit6"
type = "u8"
key = false

[[models.members]]
name = "p2_pit1"
type = "u8"
key = false

[[models.members]]
name = "p2_pit2"
type = "u8"
key = false

[[models.members]]
name = "p2_pit3"
type = "u8"
key = false

[[models.members]]
name = "p2_pit4"
type = "u8"
key = false

[[models.members]]
name = "p2_pit5"
type = "u8"
key = false

[[models.members]]
name = "p2_pit6"
type = "u8"
key = false

[[models.members]]
name = "p1_store"
type = "u256"
key = false

[[models.members]]
name = "p2_store"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3d94644939193d7628a1af138ab2169fa6d157d504a6d02c2c4f45f725741ec"
original_class_hash = "0x3d94644939193d7628a1af138ab2169fa6d157d504a6d02c2c4f45f725741ec"
abi = "abis/deployments/models/mancala_models_game_game_id.json"
name = "mancala::models::game::game_id"

[[models.members]]
name = "world_id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x77bfed0d687ffc53a5c19b5a618bb0fa48000b897a79aa321a1ea0ff581f6f"
original_class_hash = "0x77bfed0d687ffc53a5c19b5a618bb0fa48000b897a79aa321a1ea0ff581f6f"
abi = "abis/deployments/models/mancala_models_mancala_game_game_id.json"
name = "mancala::models::mancala_game::game_id"

[[models.members]]
name = "world_id"
type = "u32"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x38fafd3c63f7604540a974fa61bf61d112709c2e8efe2197a1532694e74567b"
original_class_hash = "0x38fafd3c63f7604540a974fa61bf61d112709c2e8efe2197a1532694e74567b"
abi = "abis/deployments/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_one"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_two"
type = "ContractAddress"
key = false

[[models.members]]
name = "current_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "score"
type = "u8"
key = false

[[models.members]]
name = "is_finished"
type = "bool"
key = false

[[models.members]]
name = "p1_pit1"
type = "u8"
key = false

[[models.members]]
name = "p1_pit2"
type = "u8"
key = false

[[models.members]]
name = "p1_pit3"
type = "u8"
key = false

[[models.members]]
name = "p1_pit4"
type = "u8"
key = false

[[models.members]]
name = "p1_pit5"
type = "u8"
key = false

[[models.members]]
name = "p1_pit6"
type = "u8"
key = false

[[models.members]]
name = "p2_pit1"
type = "u8"
key = false

[[models.members]]
name = "p2_pit2"
type = "u8"
key = false

[[models.members]]
name = "p2_pit3"
type = "u8"
key = false

[[models.members]]
name = "p2_pit4"
type = "u8"
key = false

[[models.members]]
name = "p2_pit5"
type = "u8"
key = false

[[models.members]]
name = "p2_pit6"
type = "u8"
key = false

[[models.members]]
name = "p1_store"
type = "u256"
key = false

[[models.members]]
name = "p2_store"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x79eee88681759e060fa0b7873332c556015a84ad9eb7b83aac1a48b61296bba"
original_class_hash = "0x79eee88681759e060fa0b7873332c556015a84ad9eb7b83aac1a48b61296bba"
abi = "abis/deployments/models/mancala_models_moves_moves.json"
name = "mancala::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x62f296d1bbb85919111799c80c70422ae5cd414b9cb0d7fee53e34a73ea97a7"
original_class_hash = "0x62f296d1bbb85919111799c80c70422ae5cd414b9cb0d7fee53e34a73ea97a7"
abi = "abis/deployments/models/mancala_models_player_game_player.json"
name = "mancala::models::player::game_player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "pit1"
type = "u8"
key = false

[[models.members]]
name = "pit2"
type = "u8"
key = false

[[models.members]]
name = "pit3"
type = "u8"
key = false

[[models.members]]
name = "pit4"
type = "u8"
key = false

[[models.members]]
name = "pit5"
type = "u8"
key = false

[[models.members]]
name = "pit6"
type = "u8"
key = false

[[models.members]]
name = "mancala"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x776c124ca27fd63720cb0df9d875ce5b8789e592a491c418136657d059bf59a"
original_class_hash = "0x776c124ca27fd63720cb0df9d875ce5b8789e592a491c418136657d059bf59a"
abi = "abis/deployments/models/mancala_models_player_player.json"
name = "mancala::models::player::player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "games_won"
type = "u256"
key = false

[[models.members]]
name = "games_lost"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x735af1f20779828915fd4d50b4d5e2c3afa0b8567c143a411f0e673171bdec3"
original_class_hash = "0x735af1f20779828915fd4d50b4d5e2c3afa0b8567c143a411f0e673171bdec3"
abi = "abis/deployments/models/mancala_models_position_position.json"
name = "mancala::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
