kind = "DojoModel"
class_hash = "0x79eee88681759e060fa0b7873332c556015a84ad9eb7b83aac1a48b61296bba"
original_class_hash = "0x79eee88681759e060fa0b7873332c556015a84ad9eb7b83aac1a48b61296bba"
abi = "manifests/dev/abis/base/models/mancala_models_moves_moves.json"
name = "mancala::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
