kind = "DojoModel"
class_hash = "0x776c124ca27fd63720cb0df9d875ce5b8789e592a491c418136657d059bf59a"
original_class_hash = "0x776c124ca27fd63720cb0df9d875ce5b8789e592a491c418136657d059bf59a"
abi = "manifests/dev/abis/base/models/mancala_models_player_player.json"
name = "mancala::models::player::player"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "games_won"
type = "u256"
key = false

[[members]]
name = "games_lost"
type = "u256"
key = false
