kind = "DojoModel"
class_hash = "0x38fafd3c63f7604540a974fa61bf61d112709c2e8efe2197a1532694e74567b"
original_class_hash = "0x38fafd3c63f7604540a974fa61bf61d112709c2e8efe2197a1532694e74567b"
abi = "manifests/dev/abis/base/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_one"
type = "ContractAddress"
key = false

[[members]]
name = "player_two"
type = "ContractAddress"
key = false

[[members]]
name = "current_player"
type = "ContractAddress"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "score"
type = "u8"
key = false

[[members]]
name = "is_finished"
type = "bool"
key = false

[[members]]
name = "p1_pit1"
type = "u8"
key = false

[[members]]
name = "p1_pit2"
type = "u8"
key = false

[[members]]
name = "p1_pit3"
type = "u8"
key = false

[[members]]
name = "p1_pit4"
type = "u8"
key = false

[[members]]
name = "p1_pit5"
type = "u8"
key = false

[[members]]
name = "p1_pit6"
type = "u8"
key = false

[[members]]
name = "p2_pit1"
type = "u8"
key = false

[[members]]
name = "p2_pit2"
type = "u8"
key = false

[[members]]
name = "p2_pit3"
type = "u8"
key = false

[[members]]
name = "p2_pit4"
type = "u8"
key = false

[[members]]
name = "p2_pit5"
type = "u8"
key = false

[[members]]
name = "p2_pit6"
type = "u8"
key = false

[[members]]
name = "p1_store"
type = "u256"
key = false

[[members]]
name = "p2_store"
type = "u256"
key = false
